### ISSUE TITLE
[1.4] Serverside crash

### ISSUE THREAD

**Issue by xenoflot** [AllTheLayers/ATLCraftCandlesMod#1]
http://pastebin.com/PWabnGrj

Looks like a similar error to the glass beads one.
Caused by: java.lang.RuntimeException: Attempted to load class bcx for invalid side SERVER

Please have a thorough hunt through for all instances of whatever might be causing this. I'll have to remove Candles until you can assure us it's server-safe!

Thanks

**Comment by AllTheLayers** [comment]
I'd forgotten that code was there for the bayberry bush. I did look through everything and the code is gone in 1.5.

Sorry about that. Thank you for posting it.

**Comment by xenoflot** [comment]
Thanks ATL. I'll give it a whirl. o/
