### ISSUE TITLE
ServerSide - Startup Crash 1.12.1

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AllTheLayers/ATLCraftCandlesMod#10]
Let me say I like the concept of this mod. I was just asking another modder if he could do something similar. I am glad someone realized torches are not the only form of light.

ATLCraftCandlesMod(MC1.12-Ver1.6).jar

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 634025224 bytes (604 MB) / 2086838272 bytes (1990 MB) up to 8520204288 bytes (8125 MB)
	JVM Flags: 8 total; -Xms1g -Xmx8g -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=40 -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSScavengeBeforeRemark -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.1.2481 126 mods loaded, 126 mods active

https://gist.github.com/P3rf3ctXZer0/40d9a342e7d9675faaa2597f78895074

So let me know when you put out a fix. Oh yes by the way I am a hardcore beta tester so let me know if you want me to test pre-releases as well.

**Comment by AllTheLayers** [comment]
Would you be willing to test this update? I haven't been able to reproduce the error, but this might fix it.

https://www.dropbox.com/s/3jrt2rg4wdg3csh/ATLCraftCandlesMod%28MC1.12-Ver1.6%29-fix.jar?dl=0

**Comment by P3rf3ctXZer0** [comment]
No problem ;) Testing now.

**Comment by P3rf3ctXZer0** [comment]
I am sorry still not working.

https://gist.github.com/P3rf3ctXZer0/b8ba0873aef49cee2a44ad3499abb965

ATLCraftCandlesMod(MC1.12-Ver1.6)-fix.jar 

Full Log - Maybe that will help
https://gist.github.com/P3rf3ctXZer0/c64017192a130ffaef70dcd1861b674e

**Comment by AllTheLayers** [comment]
Thanks for trying. Well the crash report is slightly different, so based on that I made a small change that might fix it, if you would test it again.

https://www.dropbox.com/s/emngj1ukg3fnd07/ATLCraftCandlesMod%28MC1.12-Ver1.6%29-fix2.jar?dl=0

**Comment by P3rf3ctXZer0** [comment]
No problem testing now. :)

**Comment by P3rf3ctXZer0** [comment]
Sorry it still is not fixed.
Crash log
https://gist.github.com/P3rf3ctXZer0/86be607eba2be0813df087ad6e8957b3

ATLCraftCandlesMod(MC1.12-Ver1.6)-fix2.jar

Full Server Log
https://gist.github.com/P3rf3ctXZer0/9c0d15f074dfb434f29a5f78c69647aa

**Comment by AllTheLayers** [comment]
What mods are you using? It might have something to do with the mods, because I haven't had any crashes and I've tried on single player and multiplayer.

**Comment by P3rf3ctXZer0** [comment]
I know my mod list is in the reports but for easy reading

| State | ID                    | Version                 | Source                                      | Signature                                |
	|:----- |:--------------------- |:----------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.1                  | minecraft.jar                               | None                                     |
	| UCH   | mcp                   | 9.19                    | minecraft.jar                               | None                                     |
	| UCH   | FML                   | 8.0.99.99               | forge-1.12.1-14.22.1.2481-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.22.1.2481            | forge-1.12.1-14.22.1.2481-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | ivtoolkit             | 1.3.3-1.12              | minecraft.jar                               | None                                     |
	| UCH   | securitycraft         | v1.8.2.3-hotfix         | [1.12] SecurityCraft v1.8.2.3-hotfix.jar    | None                                     |
	| UCH   | uncraftingtable       | 1.8-beta6               | [1.12]UncraftingTable-1.8-beta6.jar         | None                                     |
	| UCH   | crafttweaker          | 4.0.6                   | CraftTweaker2-1.12-4.0.6.jar                | None                                     |
	| UCH   | mtlib                 | @VERSION@               | MTLib-3.0.0.jar                             | None                                     |
	| UCH   | modtweaker            | 4.0.2                   | modtweaker-4.0.2.jar                        | None                                     |
	| UCH   | jei                   | 4.7.9.96                | jei_1.12.2-4.7.9.96.jar                     | None                                     |
	| UCH   | abyssalcraft          | 1.9.4-pre-4             | AbyssalCraft-1.12-1.9.4-pre-4.jar           | None                                     |
	| UCH   | actuallyadditions     | 1.12.1-r119             | ActuallyAdditions-1.12.1-r119.jar           | None                                     |
	| UCH   | craftstudioapi        | 1.0.0                   | CraftStudio-1.0.0.93-mc1.12-alpha.jar       | None                                     |
	| UCH   | quark                 | r1.3-110                | Quark-r1.3-110.jar                          | None                                     |
	| UCH   | animania              | 1.3.2                   | animania-1.12.1-1.3.2.jar                   | None                                     |
	| UCH   | architecturecraft     | @VERSION@               | architecturecraft-1.12-1.20.jar             | None                                     |
	| UCE   | atlcraft              | MC1.12-Ver1.6           | ATLCraftCandlesMod(MC1.12-Ver1.6)-fix2.jar  | None                                     |
	| UCH   | autoreglib            | 1.3-13                  | AutoRegLib-1.3-13.jar                       | None                                     |
	| UCH   | base                  | 3.3.0                   | base-1.12-3.3.0.jar                         | None                                     |
	| UCH   | baubles               | 1.5.1                   | Baubles-1.12-1.5.1.jar                      | None                                     |
	| UCH   | bedbugs               | @VERSION@               | BedBugs-1.12-1.0.1.jar                      | None                                     |
	| UCH   | betterunderground     | 1.0.2                   | betterunderground-1.0.2.jar                 | None                                     |
	| UCH   | bibliocraft           | 2.4.3                   | BiblioCraft[v2.4.3][MC1.12.0].jar           | None                                     |
	| UCH   | bigbeautifulbuttons   | 1.12.1-1.1.2            | bigbeautifulbuttons-1.12.1-1.1.2.jar        | None                                     |
	| UCH   | biomesoplenty         | 7.0.0.2291              | BiomesOPlenty-1.12-7.0.0.2291-universal.jar | None                                     |
	| UCH   | blockarmor            | 2.4.8                   | BlockArmor-1.12-2.4.8.jar                   | None                                     |
	| UCH   | botania               | r1.10-347               | Botania r1.10-347.jar                       | None                                     |
	| UCH   | chameleon             | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                    | None                                     |
	| UCH   | chancecubes           | 1.12.1-3.0.1.208        | ChanceCubes-1.12.1-3.0.1.208.jar            | None                                     |
	| UCH   | chisel                | MC1.12-0.0.14.18        | Chisel-MC1.12-0.0.14.18.jar                 | None                                     |
	| UCH   | chiselsandbits        | 14.7                    | chiselsandbits-14.7.jar                     | None                                     |
	| UCH   | cyclopscore           | 0.10.18                 | CyclopsCore-1.12-0.10.18.jar                | None                                     |
	| UCH   | colossalchests        | 1.6.6                   | ColossalChests-1.12-1.6.6.jar               | None                                     |
	| UCH   | contenttweaker        | 1.12-4.1.0              | ContentTweaker-1.12-4.1.0.jar               | None                                     |
	| UCH   | cosmeticarmorreworked | 1.12.1-v1               | CosmeticArmorReworked-1.12.1-v1.jar         | None                                     |
	| UCH   | crafttweakerjei       | 2.0.0                   | CraftTweaker2-1.12-4.0.6.jar                | None                                     |
	| UCH   | cucumber              | 1.0.2                   | cucumber[1.12]-1.0.2.jar                    | None                                     |
	| UCH   | modcurrency           | 1.12-1.2.0              | Currency-1.12.0-1.2.0.jar                   | None                                     |
	| UCH   | drpcore               | 0.3.2                   | Dark Roleplay Core Alpha-0.3.2.jar          | None                                     |
	| UCH   | drpmedieval           | 0.2.1.2                 | Dark Roleplay Medieval-0.2.1.2.jar          | None                                     |
	| UCH   | deathcounter          | 1.0.0                   | DeathCounter-1.12.1-1.0.0.jar               | None                                     |
	| UCH   | deathquotes           | 1.2.0                   | DeathQuotes-1.2.0-mc1.12-forge.jar          | None                                     |
	| UCH   | dimensionrules        | 1.1                     | DimensionRules-MC1.12-1.1.jar               | None                                     |
	| UCH   | dungeontactics        | DT-0.13.7               | DungeonTactics-1.12-0.13.7.jar              | None                                     |
	| UCH   | extrabitmanipulation  | 1.12-3.2.1              | ExtraBitManipulation-1.12-3.2.1.jar         | None                                     |
	| UCH   | flatcoloredblocks     | mc1.12-6.5              | flatcoloredblocks-mc1.12-6.5.jar            | None                                     |
	| UCH   | floricraft            | 4.2.2                   | Floricraft-1.12-4.2.2.jar                   | None                                     |
	| UCH   | foamfix               | 0.8.0-1.12              | foamfix-0.8.0-1.12-law.jar                  | None                                     |
	| UCH   | mantle                | 1.12-1.3.1.21           | Mantle-1.12-1.3.1.21.jar                    | None                                     |
	| UCH   | natura                | 1.12-4.3.0.17           | Natura-1.12-4.3.0.17.jar                    | None                                     |
	| UCH   | forestry              | 5.5.6.197               | forestry_1.12.2-5.5.6.197.jar               | None                                     |
	| UCH   | ftbl                  | 0.0.0                   | FTBLib-4.1.3.jar                            | None                                     |
	| UCH   | ftbu                  | 0.0.0                   | FTBUtilities-4.1.3.jar                      | None                                     |
	| UCH   | cfm                   | 4.1.5                   | furniture-4.1.5-1.12.jar                    | None                                     |
	| UCH   | gardenstuff           | 1.12-2.1.0              | GardenStuff-1.12-2.1.0.jar                  | None                                     |
	| UCH   | hardcoredarkness      | 1.9                     | HardcoreDarkness-MC1.12-1.9.jar             | None                                     |
	| UCH   | hidenames             | 1.4                     | HideNames-1.12-1.4.jar                      | None                                     |
	| UCH   | inventorytweaks       | 1.63+beta.108.6ff67c4   | InventoryTweaks-1.63+beta.108.jar           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | itorch                | 1.2.0                   | itorch-1.2.0.jar                            | None                                     |
	| UCH   | jeibees               | 0.9.0.4                 | jeibees-0.9.0.4-mc1.12.1.jar                | None                                     |
	| UCH   | journeymap            | 1.12.1-5.5.0b4          | journeymap-1.12.1-5.5.0b4.jar               | None                                     |
	| UCH   | keepinginventory      | 2.3                     | KeepingInventory-1.12.1-2.3.jar             | None                                     |
	| UCH   | mercurius_updater     | 1.0                     | MercuriusUpdater-1.12.1.jar                 | None                                     |
	| UCH   | metamorph             | 1.1.4                   | metamorph-1.1.4-1.12.1.jar                  | None                                     |
	| UCH   | minecolonies          | 1.12.1-0.8.4026         | minecolonies-universal-1.12.1-0.8.4026.jar  | None                                     |
	| UCH   | morebeautifulbuttons  | 1.12.1-1.6.0.13         | morebeautifulbuttons-1.12.1-1.6.0.13.jar    | None                                     |
	| UCH   | morebeautifulplates   | 1.12.1-1.0.2            | morebeautifulplates-1.12.1-1.0.2.jar        | None                                     |
	| UCH   | shetiphiancore        | 3.5.2                   | shetiphiancore-1.12.0-3.5.2.jar             | None                                     |
	| UCH   | terraqueous           | 1.4.3                   | terraqueous-1.12.0-1.4.3.jar                | None                                     |
	| UCH   | multibeds             | 1.4.3                   | multibeds-1.12.0-1.4.3.jar                  | None                                     |
	| UCH   | multimine             | 1.5.7                   | MultiMine-1.12.1.jar                        | None                                     |
	| UCH   | multistorage          | 1.4.3-TEST-1            | multistorage-1.12.0-1.4.3-TEST-1.jar        | None                                     |
	| UCH   | mysticalagriculture   | 1.6.4                   | mysticalagriculture-1.12-1.6.4.jar          | None                                     |
	| UCH   | tconstruct            | 1.12-2.7.3.30           | TConstruct-1.12-2.7.3.30.jar                | None                                     |
	| UCH   | mysticalagradditions  | 1.2.4                   | mysticalagradditions[1.12]-1.2.4.jar        | None                                     |
	| UCH   | naturescompass        | 1.5.0                   | NaturesCompass-1.12-1.5.0.jar               | None                                     |
	| UCH   | netherportalfix       | 5.3.9                   | NetherPortalFix_1.12.1-5.3.9.jar            | None                                     |
	| UCH   | recipehandler         | 0.9                     | NoMoreRecipeConflict-0.9(1.12).jar          | None                                     |
	| UCH   | neid                  | 1.5.4.1                 | NotEnoughIDs-1.5.4.1.jar                    | None                                     |
	| UCH   | powerinventory        | 2.3.1                   | OverpoweredInventory-1.12-2.3.1.jar         | None                                     |
	| UCH   | harvestcraft          | 1.12.1c                 | Pam's HarvestCraft 1.12.1c.jar              | None                                     |
	| UCH   | plants                | 1.2.0                   | Plants-1.12-1.2.0.jar                       | None                                     |
	| UCH   | plustic               | 6.3.1.0                 | plustic-6.3.1.0.jar                         | None                                     |
	| UCH   | thutcore              | 5.11.0                  | thutcore-5.11.0.jar                         | None                                     |
	| UCH   | pokecube              | 6.21.3                  | Pokecube_Core-6.21.3.jar                    | None                                     |
	| UCH   | reccomplex            | 1.4.5                   | RecurrentComplex-1.4.5.1.jar                | None                                     |
	| UCH   | theoneprobe           | 1.4.18                  | theoneprobe-1.12-1.4.18.jar                 | None                                     |
	| UCH   | thut_wearables        | 3.1.0                   | thut_wearables-3.1.0.jar                    | None                                     |
	| UCH   | pokecube_adventures   | 6.11.2                  | Pokecube Revival-6.11.2.jar                 | None                                     |
	| UCH   | pokecube_mobs         | 2.14.8                  | Pokecube Mobs-2.14.8.jar                    | None                                     |
	| UCH   | pokecube_moves        | @VERSION@               | Pokecube Mobs-2.14.8.jar                    | None                                     |
	| UCH   | pokecube_origin       | @VERSION@               | Pokecube Mobs-2.14.8.jar                    | None                                     |
	| UCH   | pokecube_compat       | 1.0                     | Pokecube Revival-6.11.2.jar                 | None                                     |
	| UCH   | pceditmod             | 1.10.2-2.0.0            | Pokecube_Core-6.21.3.jar                    | None                                     |
	| UCH   | pokecube_ml           | 0.1.0                   | Pokecube_Core-6.21.3.jar                    | None                                     |
	| UCH   | prefab                | 1.3.0.10                | prefab-1.3.0.10.jar                         | None                                     |
	| UCH   | realfilingcabinet     | 0.1.2                   | realfilingcabinet-1.12.1-0.1.2.jar          | None                                     |
	| UCH   | recycler              | 1.4.8                   | recycler-1.4.8-1.12.0.jar                   | None                                     |
	| UCH   | rftools               | 6.13                    | rftools-1.12-6.13.jar                       | None                                     |
	| UCH   | rftoolsdim            | 5.05                    | rftoolsdim-1.12-5.05.jar                    | None                                     |
	| UCH   | roots                 | 0.103                   | roots-2-0.103.jar                           | None                                     |
	| UCH   | rustic                | 0.4.2.1                 | rustic-0.4.3.jar                            | None                                     |
	| UCH   | silentlib             | 2.2.8                   | SilentLib-1.12-2.2.8-88.jar                 | None                                     |
	| UCH   | scalinghealth         | 1.2.2                   | ScalingHealth-1.12-1.2.2-70.jar             | None                                     |
	| UCH   | seedcopy              | 3.0.5                   | SeedCopy-1.9-3.0.5.jar                      | None                                     |
	| UCH   | silentgems            | 2.5.1                   | SilentsGems-1.12-2.5.1-225.jar              | None                                     |
	| UCH   | sgextraparts          | 1.4.0                   | SGExtraParts-1.12-1.4.0-30.jar              | None                                     |
	| UCH   | signpic               | 2.8.1                   | SignPicture-1.12.1-2.8.1-universal.jar      | None                                     |
	| UCH   | simpledimensions      | 1.3.1                   | SimpleDimensions-MC1.12-1.3.1.jar           | None                                     |
	| UCH   | simplyconveyors       | 3.0.6                   | SimplyConveyors-4.0.4.jar                   | None                                     |
	| UCH   | storagedrawers        | 1.12-5.2.5              | StorageDrawers-1.12.1-5.3.2.jar             | None                                     |
	| UCH   | storagedrawersextra   | @VERSION@               | StorageDrawersExtras-1.12-3.1.0.jar         | None                                     |
	| UCH   | structpro             | 4.0                     | structpro-4.0-1.12.1.jar                    | None                                     |
	| UCH   | thuttech              | 6.0.5                   | thuttech-6.0.5.jar                          | None                                     |
	| UCH   | tcomplement           | ${version}              | TinkersComplement-1.12.1-0.2.0.jar          | None                                     |
	| UCH   | tinkertoolleveling    | 1.12-1.0.2b.DEV.1a79301 | TinkerToolLeveling-1.12-1.0.2b.jar          | None                                     |
	| UCH   | topaddons             | 1.12-0.15.1             | topaddons-1.12-0.15.1.jar                   | None                                     |
	| UCH   | buildhelper           | 0.5.0                   | torojimaBuildHelper-1.0.0.jar               | None                                     |
	| UCH   | trashslot             | 8.4.6                   | TrashSlot_1.12.1-8.4.6.jar                  | None                                     |
	| UCH   | treechopper           | 1.2.3                   | TreeChopper-1.12.1-1.2.3.jar                | None                                     |
	| UCH   | upsizer               | 4.0                     | upsizer-mc1.12.1-4.0.jar                    | None                                     |
	| UCH   | vc                    | 5.0.6                   | ViesCraft-1.12.0-5.0.6.jar                  | None                                     |
	| UCH   | wopper                | 1.12-r5                 | Wopper-1.12-r5.jar                          | None                                     |
	| UCH   | worldedit             | 6.1.8                   | worldedit-forge-mc1.12-6.1.8-dist.jar       | None                                     |
	| UCH   | xtones                | 1.12-1.0.6-9            | Xtones-1.12-1.0.6-9.jar                     | None                                     |
	| UCH   | yabba                 | 1.12-1.0.2              | YABBA-1.12-1.0.2.jar                        | None                                     |

**Comment by P3rf3ctXZer0** [comment]
[List.txt](https://github.com/AllTheLayers/ATLCraftCandlesMod/files/1319375/List.txt)

**Comment by Tokeli** [comment]
I've been getting this error too!
[Crash report gist.](https://gist.github.com/Tokeli/1295894ca6148dab105821f481d61f47)

Since it says "ModelLoader", could it be because it's missing this mod? https://minecraft.curseforge.com/projects/modelloader Nothing on the page mentions it, and there's no dependency on Curse, but maybe that was overlooked!

**Comment by Ivorforce** [comment]
Since @P3rf3ctXZer0 brought me here - ModelLoader does not exist on a dedicated server (see the SideOnly annotation on the class). You need a Sided Proxy setup where only on the client you register the rendering aspects of your mod. 

See https://github.com/Ivorforce/RecurrentComplex/blob/master/src/main/java/ivorius/reccomplex/RecurrentComplex.java#L57-L58 (and the below proxy.registerRenderers call) for an example implementation.

**Comment by AllTheLayers** [comment]
Thank you, @Ivorforce! That explained it clearly and I think I've fixed it. I appreciate you taking the time to help.

@P3rf3ctXZer0 would you try this fix? I think it should work this time.

https://www.dropbox.com/s/rcm6foo7nufp02r/ATLCraftCandlesMod%28MC1.12-Ver1.7%29-fixtest.jar?dl=0

**Comment by P3rf3ctXZer0** [comment]
Alright testing now and thanks for your help again @Ivorforce

**Comment by P3rf3ctXZer0** [comment]
Yes its been fixed.

**Comment by AllTheLayers** [comment]
Thank you for your help, @P3rf3ctXZer0.
