### ISSUE TITLE
Odd Spawning

### ISSUE THREAD

**Issue by BuilderDan** [AllTheLayers/ATLCraftCandlesMod#13]
Hello,

Your mod is quite wonderful, the only slight problem is the adorable little village house that spawns in villages. The way it is spawned is quite awful sadly if it is spawned in water it does this:
image
![image](https://user-images.githubusercontent.com/19805371/31855083-317e004e-b658-11e7-887b-378474a2ff14.png)

And inland it cuts through the earth...

I can handle the land one but the water spawning is just not pretty to see xD I'd love to see the mod updated with better spawning for the little hut, currently it doesn't work very well alongside Mo'Villages due to those strange spawning features...

**Comment by BuilderDan** [comment]
![image](https://user-images.githubusercontent.com/19805371/31855091-6f3707be-b658-11e7-98e0-7d1a35d238ac.png)

![image](https://user-images.githubusercontent.com/19805371/31855095-748bfce2-b658-11e7-82ca-563326eee81f.png)

**Comment by BuilderDan** [comment]
I can live with it, but it's just not attractive and I figured you'd want to know ;D

**Comment by AllTheLayers** [comment]
Thanks for the report!

This should be fixed in MC1.12-Ver1.9.
