### ISSUE TITLE
[Suggestion] OreDict usage

### ISSUE THREAD

**Issue by drakray** [AllTheLayers/ATLCraftCandlesMod#2]
I think your candle should use oreDict for dyeing. Mainly because I tend to use alterate way of dyeing, mainly for Lapis usage(I remove dyeBlue from Lapis, and use Botania blue floral powder as dye, with a custom recipe lapis->powder)

Also, making your wax have the materialPressedwax oreDict name(same as Pam's), and using this as ingredient would remove LOTS of duplicate(~280 JEI's pages)

As always, that's only my opinion/suggestion, it's your call at the end ;)

Keep up the good work, this mod is Amazing!

-drakray

**Comment by ghost** [comment]
@drakray has a point. Hordes of items each in 16 colors of wax, multiple metals and shifted up/down/left/right makes for a lot of recipes cluttering JEI. (Still a must-have mod.)

**Comment by AllTheLayers** [comment]
All candle recipes now use the ore dictionary for dyes and materialPressedwax in MC1.12-Ver1.7.
