### ISSUE TITLE
Chandeliers vanishing after "I'm not connected to a rope" check

### ISSUE THREAD

**Issue by xenoflot** [AllTheLayers/ATLCraftCandlesMod#4]
ATL Candles v1.5 - running in SMP

Broken normally, the chandelier drops as an item. However if, due to the chain or rope being broken, when the chandelier makes the "am I correctly suspended" check, it vanishes without dropping as an item. This also happens when you accidentally miss the tiny hitbox of the rope and accidentally place it against the side of the rope.

Tested with a combination of ropes and chains and chandeliers of varying materials.

Side note: If it's possible to make the hitbox bigger than the model, I'd suggest that's worthwhile in the case of ropes and chains. Trying to target them from end-on is not easy for my old-man eyes :-)

Cheers!

**Comment by Danklor** [comment]
I have also had disappearing chandeliers in SSP MC 1.10.2, ATL Candles 1.5, Forge 12.18.2.2121.  This also happens if a chandelier is placed anywhere that does not have anything directly above it, but it stays put if it is under anything including a torch on the wall.

**Comment by AllTheLayers** [comment]
This has been fixed in MC1.12-Ver1.6.
