### ISSUE TITLE
Request: Add some hardness to your blocks

### ISSUE THREAD

**Issue by xenoflot** [AllTheLayers/ATLCraftCandlesMod#6]
At the moment, candles, chandeliers and whatnot can be broken with a single punch. This can lead to accidental breakage if one is clumsy. It would be nice if they could have some hardness so as to resist such accidental breakage.

Cheers!

**Comment by AllTheLayers** [comment]
Thanks for the suggestion. This has been added in MC1.12-Ver1.6.
